### ISSUE TITLE
Add all tasks for COCO dataset formats

### ISSUE THREAD

**Issue by german36-del** [javierganan99/resize-dataset#1]
Need for support for all **COCO** dataset formats that will be:

- [ x ] COCO Detection
- [ x ] COCO Segmentation
- [ x ] COCO Panoptic 
- [   ] COCO Keypoint detection
- [   ] COCO Image captioning
- [   ] COCO Dense pose
 
**🚨 IMPORTANT:** 
Follow the abstract class convention.

**Comment by german36-del** [comment]
Main ideas to consider here and my proposals:

- _What should we store in the output json?_ 
I would skip the info or create our own, the images I would keep the valid images (Images that we are able to read) and in the annotations the original annotations with the task field modified (If task == keypoint keypoint modified). Categories should not be changed.
**NOTE**
At the moment it is not changed the image size, just appending another annotation with the new annotations. I dont know if this make sense. In COCO Keypoint there is an example where this is done in other way. In my opinion we should change the image size and the annotations.

- _COCO Image Captioning_ 
Here I would not modify the output json. Just the image size.

@javierganan99

**Comment by javierganan99** [comment]
I will answer the above comment point by point:

- In the output json, in the case of the COCO format, I think we should maintain all the original annotations, modifying only the fields related to scaling. I do not know what do you mean with task field, I do not find it in COCO fields.
ANSWAER TO NOTE: This is an error. I am not scaling the images' dimensions in the JSON annotations. This is being addressed on #4.
- I agree with your last point.
